# Generated by Django 5.2.13 on 2026-05-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
    ]
