# Generated by Django 5.2.13 on 2026-04-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_items_cart_status_cart_user_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('finished', 'Finished')], default='active', max_length=50),
        ),
    ]
